# Generated by Django 4.0.5 on 2022-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expire_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_on',
            field=models.DateField(null=True),
        ),
    ]
