# Generated by Django 4.0.5 on 2022-06-29 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_alter_notification_expire_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(max_length=250)),
                ('notification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
