# Generated by Django 4.0.5 on 2022-06-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_userread_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userread',
            old_name='notification_id',
            new_name='notification',
        ),
        migrations.RenameField(
            model_name='userread',
            old_name='user_id',
            new_name='user',
        ),
    ]
