# Generated by Django 4.0.5 on 2022-06-16 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptomps',
            new_name='Symptoms',
        ),
        migrations.RenameField(
            model_name='symptoms',
            old_name='symptompValues',
            new_name='symptomValues',
        ),
    ]
