# Generated by Django 4.0.5 on 2022-07-21 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodStartDay', models.DateField(null=True)),
                ('periodEndDay', models.DateField(null=True)),
                ('cycleEndDay', models.DateField(null=True)),
                ('ovDate', models.DateField(null=True)),
                ('periodLen', models.IntegerField(default=0, null=True)),
                ('cycleLen', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
