# Generated by Django 4.0.5 on 2022-06-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='last_date_of_period',
            field=models.DateTimeField(null=True),
        ),
    ]
