# Generated by Django 4.0.5 on 2022-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalData', '0002_personaldata_last_date_of_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='last_date_of_period',
            field=models.DateField(null=True),
        ),
    ]
